### ISSUE TITLE
Streamline repositories

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron-and-OpenMV#11]
There are 8 repositories in this organization, but i am not sure if we need them all. Can we remove/reduce/combine repositories if they are not critical or if they are redundant?

- `.github`- keep, to explain the Github org
- `OMVmodel` - keep, this is the code to make the openMV model (but we can remove the openMV code, since it might be duplicate with the OpenMV code in `Boron-and-OpenMV`?
- `Boron-and-OpenMV` - the one we all seem to be working in, which seems to be critical
- `TinyCamPublish1` - needed?
- `Boron` - is this needed? or does `Boron-and-OpenMV` supersede it?
- `Example-Repo` - needed still?
- `Boron-and-OpenMV-Basics ` - is this needed? or does `Boron-and-OpenMV` supersede it?
- `Boron` - is this needed? or does `Boron-and-OpenMV` supersede it?
- `Honors-Thesis-Requirements ` - are you using this? if not, lets delete... 

(cc: @SUPScientist , i want your opinion/perspective in case i am missing something)

**Comment by SUPScientist** [comment]
First a quick step back then I'll dive into the specific repos.

The rationale had been that the project was hitting key milestones and it seemed like there could be some value in "locking in" those milestones. For instance, once the UART comms were working but before sleep and cellular transmission had been activated, I recommended that a repo be left as is with just UART comms and that a new one be created for the next step for, e.g., adding cellular. The thinking was that a newbie to the org might find value in these discrete stopping points. Unfortunately I think it ended up being used a little inconsistently, so there aren't many clean discrete stopping points as I'd anticipated when looking forward a few months ago. 

Current state is that, to my knowledge, `Boron-and-OpenMV` is the only actively maintained repo. It should have Boron and OpenMV firmware and the ML model, a wiring diagram, etc.—everything in a single self-contained repo.

My recommendation:
- Definitely keep `Boron-and-OpenMV`
- Definitely keep `.github`
- Keep `Boron-and-OpenMV-Basics` for now as there may be supporting documentation in that repo. 
- Nothing with unique code or other content in the other repos to my knowledge.

**Comment by BentleySettin** [comment]
Sounds good. I can delete the other ones.

**Comment by BentleySettin** [comment]
Looks like repos have to be deleted by whoever created them. @ebgoldstein @SUPScientist

**Comment by ebgoldstein** [comment]
archived repositories, and then adjusted the org readme
