### ISSUE TITLE
first draft parts printed

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron-and-OpenMV#18]
print parts for dry fitting/inspection

**Comment by ebgoldstein** [comment]
@jacobstasiewicz - can you post a picture of the parts here when they are done/fitted? then feel free to close the issue

**Comment by jacobstasiewicz** [comment]
![image](https://github.com/TinyCamML/Boron-and-OpenMV/assets/72474059/3168b206-1334-49dd-86b4-7d66653b3a9a)
![image](https://github.com/TinyCamML/Boron-and-OpenMV/assets/72474059/b40d2c27-beba-4ed3-8150-e538d7f056ea)
![image](https://github.com/TinyCamML/Boron-and-OpenMV/assets/72474059/b689f07a-e484-423b-9a28-fa020f61e595)
