### ISSUE TITLE
save a csv of all image names

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron-and-OpenMV#25]
make csv to save images on openMV

**Comment by efarq** [comment]
commit 3a03ea4 - made some progress with this. Right now it saves the datetime and "flood" or "no flood" to a .txt file but I'm sure we can easily change that if you prefer .csv. It takes a round or two of the boron running with cellular for this to work properly. So it might just need a bit of cleaning in the future

**Comment by ebgoldstein** [comment]
i have changed this a bit .. see #26
