### ISSUE TITLE
Integrate google sheets with particle console

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron-and-OpenMV#3]

**Comment by BentleySettin** [comment]
I want to verify I am taking the write steps @SUPScientist 

I added a new integration using the google cloud platform because we agreed to send it to google sheets.

**Comment by SUPScientist** [comment]
Noted. This is lower priority than getting the UART comms working again, so we'll focus on UART (flood/no flood) and then come back to this.

**Comment by BentleySettin** [comment]
@SUPScientist With Uart comms fixed I believe I am ready to integrate! Whoot whoot

**Comment by BentleySettin** [comment]
@SUPScientist do you have time to meet this week to work on the integration?

**Comment by SUPScientist** [comment]
Unsure, sorry, but I'll try.  (Off-topic, but please continue to clean up the overall organization, including the homepage which has several repository descriptions that make them sound identical even though I think they're not. If you're stalled in coding work, there's plenty of documentation work (and thesis writing!) to be done as well so don't let me hold you up on general progress.)

**Comment by BentleySettin** [comment]
@SUPScientist @ebgoldstein I am struggling to find where to edit the "About" page to update and better detail the descriptions. I looked up how even though I have done it before. It says use the settings gear in the upper right to edit but I do not have one. 

Am I missing something? :)

**Comment by SUPScientist** [comment]
See https://github.com/TinyCamML/.github/issues/1

**Comment by SUPScientist** [comment]
Currently building the webhook to execute the publishing of data from Boron to Particle cloud to google sheets. Relies on an `eventName` which is currently `eventName = "FloodorNo"`:
https://github.com/TinyCamML/Boron-and-OpenMV/blob/a73a2d89ecc041749dbf780870dfa5da932aa2f8/Firmware/PublishBoronCode/src/TinyCamPublish.ino#L26

Do not change `eventName` or else integration will fail. More progress to come...

**Comment by SUPScientist** [comment]
Read-only access to google sheet here: https://docs.google.com/spreadsheets/d/11ocVnjbdwYJO1UnGhrpfUw7a2iHKmkT3kHaA8BR1ntw/edit?usp=sharing

**Comment by SUPScientist** [comment]
Following docs linked in https://github.com/COAST-Lab/Open-Water-Level/issues/24

**Comment by SUPScientist** [comment]
Integration created and ready for testing. See https://github.com/COAST-Lab/Open-Water-Level/tree/main/Particle_Integration for documentation (which we ought to copy and paste here, too, including .js and .json files). 
**IMPORTANT**: let's test this together in person to ensure correct functionality and non abuse of cellular connection. We'll set `PUBLISHING` to 1 here: https://github.com/TinyCamML/Boron-and-OpenMV/blob/a73a2d89ecc041749dbf780870dfa5da932aa2f8/Firmware/PublishBoronCode/src/TinyCamPublish.ino#L14

and `SECONDS_BETWEEN_MEASUREMENTS` to 360 here: https://github.com/TinyCamML/Boron-and-OpenMV/blob/a73a2d89ecc041749dbf780870dfa5da932aa2f8/Firmware/PublishBoronCode/src/TinyCamPublish.ino#L33

Then recompile/flash, then watch to see if the integration works. Leaving issue open till we can confirm functionality.

**Comment by BentleySettin** [comment]
This works! Made recommended changes of setting publishing to 1 and measurements every 360 seconds. 

Here is the google sheets which shows successful integration and collection: https://docs.google.com/spreadsheets/d/11ocVnjbdwYJO1UnGhrpfUw7a2iHKmkT3kHaA8BR1ntw/edit#gid=0
