### ISSUE TITLE
different repository for analysis codes?

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron-and-OpenMV#42]
All,
do we want to put analysis codes in a different repository? [I started one and put my notebook from today in there](https://github.com/TinyCamML/DeploymentAnalysis)

**Comment by ebgoldstein** [comment]
(I see you code @SUPScientist - and i tried not to be duplicative (i.e., i did not add any met/ocean data yet)

**Comment by SUPScientist** [comment]
Happy to follow your lead—this works for me! Should I move (or feel free to do so yourself) mine over to the new repo, then?

**Comment by anardek** [comment]
It doesn’t matter to me as long as there are no links to the photo storage.

**Comment by ebgoldstein** [comment]
done
