### ISSUE TITLE
Optimize sleep state

### ISSUE THREAD

**Issue by SUPScientist** [TinyCamML/Boron-and-OpenMV#5]
Current sleep configuration is the following:  
https://github.com/TinyCamML/Boron-and-OpenMV/blob/a73a2d89ecc041749dbf780870dfa5da932aa2f8/Firmware/PublishBoronCode/src/TinyCamPublish.ino#L139-L145

Check Particle docs to ensure that `SystemSleepMode::ULTRA_LOW_POWER` and `NETWORK_INTERFACE_CELLULAR, SystemSleepNetworkFlag::INACTIVE_STANDBY` are optimal for current sampling scheme (i.e. 6-min sampling interval).

**Comment by ebgoldstein** [comment]
is this still relevant? or should it be closed for now?

**Comment by SUPScientist** [comment]
Relevant as likely needed enhancement, but nearly redundant with https://github.com/TinyCamML/Boron-and-OpenMV/issues/1 so closing here in favor of that one.
