### ISSUE TITLE
Initial enclosure design

### ISSUE THREAD

**Issue by SUPScientist** [TinyCamML/Boron-and-OpenMV#8]
### Need
Design housing/enclosure for Boron, OpenMV, internal lipo battery (if needed), and external solar panel/battery.

### Steps
- [x] Select polycase with dimensions to fit all parts
- [x] Design placement for penetrators/cable glands on polycase
- [x] Design placement for camera and window/sun glare shield if needed
- [x] Design bracket to mount polycase and solar panel together

**Comment by SUPScientist** [comment]
Some reference materials exist in related repo, such as a bracket for Voltaic panel/battery and polycase: https://github.com/COAST-Lab/Open-Water-Level/tree/main/Fabrication/Enclosure%20and%20Assembly/Voltaic-Polycase-Bracket. Note that bracket was designed for printing on Form 3 and was made shorter than might be desired given printer limitations. Designed for polycase here https://github.com/COAST-Lab/Open-Water-Level/blob/main/Fabrication/Datasheets/polycase_2d_drawings.pdf and Voltaic bracket here https://github.com/COAST-Lab/Open-Water-Level/blob/main/Fabrication/Datasheets/Voltaic_Bracket_BK102_dwg.pdf.

**Comment by SUPScientist** [comment]
@ebgoldstein, I tried to assign this to @jacobstasiewicz but he's not a member of the org and I'm not an owner/don't have permissions to add new members. Could you pull him into the org?

**Comment by ebgoldstein** [comment]
@jacobstasiewicz, I'm looping you into this issue re: designng enclosure for the openMV+particle system

To make everyone aware, Jacob and I discussed:
- we need a hole for a cable gland,  but we might not need other cuts.
- 3D printing a mounting system
- I will design a PCB with female headers for the 2 boards to pop into

We discussed options for the camera field of view:
- do we want a clear lid or solid lid?
- do we want a camera dome?
- do we want a hile& visor

**Comment by ebgoldstein** [comment]
finding or deisgn/printing a bracket connecting polycase to solar panel (https://github.com/COAST-Lab/Open-Water-Level/blob/main/Fabrication/Enclosure%20and%20Assembly/Voltaic-Polycase-Bracket/Polycase-Voltaic-Bracket%20v12.stl)

**Comment by SUPScientist** [comment]
If this design serves as the basis for a new design for this TinyCamML project, please let me know early in the design process. 

Two improvements needed to that design:
1. Slots for mating the solar panel bracket with the custom 3D printed bracket referenced above could be shifted a couple mm for better alignment 
2. It'd be valuable to have material under the top mounting holes on the solar panel bracket to avoid tightening a hose clamp in the top to the extent that it pulls the top of the solar bracket flush with a tree which would result in a non-perpendicular camera angle

**Comment by ebgoldstein** [comment]
@jacobstasiewicz:

can you commit the design files and a draft BOM to a new folder in this repository called 'hardware' then close this issue?

I will open a range of issues related to hardware design based on our discussion today, they will all be tagged with 'enclosure' and 'enhancement'

**Comment by ebgoldstein** [comment]
this is done... #22 is focused on uploading files
